version: '3'
services:
  headnode:
    image: "kastilochagin/headnode-image:hw"
    environment:
      - container=docker
    ports:
      - "9870:9870"
      - "8088:8088"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      #- /opt/mount1:/opt/mount1
      #- /opt/mount2:/opt/mount2
  worker:
    image: "kastilochagin/worker-image:hw"
    environment:
      - container=docker
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      #- /opt/mount1:/opt/mount1
      #- /opt/mount2:/opt/mount2
